language: scala
scala:
- 2.11.7
script: sbt clean test
jdk:
- openjdk11
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
env:
  global:
  - secure: TQdSqXO4Uy+k1LYt8z92ti5YEOXS2GwUOmYASbFRedk0sgIAxEiHk7rWaV9wCHe+G+xRUnEg6ylcYKnXVuN7aikPlkmrS0ykspc5IZppU0eBx0pPRczAFkN9TsaT7XlNhlHw2BXIwlIQFJzxPUnOmvu5rruoB022uTVIyjXCYfW+RhDy/NFdvE3iIjIizdvT7p3oZDeH1bXK07qtDJs9AqxPrTbXkH9ivzl78nxoC8VHFKTKXFPLHzRExmmBWS86VPbeKD6sk5ogZhM3pXkuNodNCD62Gi8WHr9M8ogJhWuvaX/FDibsF8etNck+D1qVVoNk2zJ689TVCknM1F2ffOFqFO7wBnqAsyKOjqiGkgm5xRBJeZ5VIlzcSEGasMtotEZKHpx93SZClBQk5IGM84vrs0IOwf2z0D0x//+VOKt9Uh/MTFLJaJF1U9eT0/1XMyN6Q4D07v+HU/QbtATWsaaHuNEdgKy23cH9gnl+yhVL6BAQdjY7URxFGjJapZdAsudj3oQw2OIEFSHmBOVEhirzBQ4KYyHyWYfhz/XKfI9a0heiOn+cq1lYc9V1MbU78q8CNuNZX8HapnQJX5GIPGT0m7T5hTvN1ffZyeyZWzDkvgWFg6eh6SosOQFNNJ7hugbIX1fe6OwCYSKuEUcd0AFNw/WZfFR7BUAVmPjeyVw=
  - secure: d14SrT+fv3zvVx49G47qk0SO//BBAr3tOc8yyaZh6Olvb/nF8RQN5WfipDGoUHcWjGM9u88DyBu2CsGshlKp97mW7NpPCaTH3mZ9oOCU7b2wJcpiqaYUWefPrDZ1+hd612k6Y4I38+NRl3OcdKGJSUJUCxe+3ssDPCZWM9tScwNqkN+Rz3iBO2wgWXgBYfF7fIaJ6EDkO+I2/kzO9lKoVgcV02WTbvi0hhstfaoZs/UwUQdIxo5kUrXw2jzqb8xfcG+dThWLfGbOpJRfwJlupstxwuf6/SATuBENVHJ+MS9e8OpJX4uQc9KUUx4mF1VrUu0zk9ydW23Yh1FHxJ4jWC7K3L9DHYXNjynZK2IFbjzPUquUu6Y40qG3XF+m3qjca7Y4nWhr4zgjW+2f2faM1T2zbGny+Bf1p1NDT6NKs0CIIe4GIKpF6/DSEbu+LIXOV1jI1sVA0o/bGnfFfwUe8pZLA7gnxTKaIhDywsLoJmHSbvridSHzN8QHPu/VYn4rnHdhmisN+5WK2in+LXT9aUHJr+hBSYWJkjdl30RjnIjH58Y/Zd5FR4YYdHNlcSDgli5nBhgVbwfNh/pUo9nbf8OHALzzHDXIF1BKGfYOzUF2LA1Pq1JMCYWopyJyZQuukttI3MJXILHTvUAx9XZjgGC1/pSEDXdLcEY+rFEEwvQ=
