/{ident8}:
  get:
    responses:
      200:
        body:
          application/json:

/{ident8}/bbox:
  get:
    responses:
      200:
        body:
          application/json:

/csv:
  get:
    responses:
      200:
        body:
          application/json:

/{ident8}/sectie/:
  get:
    responses:
      200:
        body:
          application/json:

/{ident8}/sectie/via/positie:
  get:
    responses:
      200:
        body:
          application/json:
