#%RAML 1.0
---
title: test01
version: 1.0
mediaType: application/json

traits:
  - error404:               !include traits/error404.raml

types:
  link:                     !include schemas/link.json
  method:                   !include schemas/method.json
  user:                     !include schemas/user.json
  error:                    !include schemas/error.json
  animal:                   !include schemas/animal.json
  cat:                      !include schemas/cat.json
  zoo:                      !include schemas/zoo.json
  paged-list:               !include schemas/paged-list.json
  strange-chars:            !include schemas/strange-chars.json
  tree:                     !include schemas/tree.json
  bbox:                     !include schemas/geojson/bbox.json
  crs:                      !include schemas/geojson/crs.json
  many-fields:              !include schemas/many-fields.json
  attributes:               !include schemas/attributes.json
  empty-object-field:       !include schemas/empty-object-field.json
  geometry:                 !include schemas/geojson/geometry.json
  connections:              !include schemas/gurumeditator/connections.json
  messages:                 !include schemas/gurumeditator/messages.json
  car:                      !include schemas/relativeid/car.json
  engine:                   !include schemas/relativeid/engine.json
  fuel:                     !include schemas/relativeid/fuel.json
  SimpleForm:
    type: object
    properties:
      firstname: string
      lastname: string
      age?: integer
  LongPagedList:
    type: object
    typeVariables: [T, U]
    properties:
      count:
        type: integer
      elements:
        type: array
        items:
          type: object
          genericType: T
      owner:
        type: object
        genericType: U
  Book:
    type: object
    discriminator: kind
    properties:
      isbn:
        type: string
        required: true
      title:
        type: string
        required: true
      genre:
        type: string
      author:
        type: Author
        required: true
  Author:
    type: object
    properties:
      firstName:
        type: string
        required: true
      lastName:
        type: string
        required: true
  WithVillain:
    type: object
    properties:
      villain:
        type: string
  ComicBook:
    type: [Book, WithVillain]
    properties:
      hero:
        type: string
  SciFiComicBook:
    type: ComicBook
    discriminatorValue: ScienceFictionComicBook
    properties:
      era:
        type: string
  Stars:
    type: object
    properties:
      name: string
      fans:
        type: LongPagedList
        genericTypes: [user, integer]
  Heroes:
    enum:
     - Spyderman
     - Superman
     - Daredevil
  birthday:
    type: date-only # no implications about time or offset
  lunchtime:
    type: time-only # no implications about date or offset
  fireworks:
    type: datetime-only # no implications about offset
  created:
    type: datetime
    format: rfc3339 # the default, so no need to specify
  If-Modified-Since:
    type: datetime
    format: rfc2616 # this time it's required, otherwise, the example format is invalid
  TwentyThreeFields:
    type: object
    properties:
      one:
        type: string
      two:
        type: string
      three:
        type: string
      four:
        type: string
      five:
        type: string
      six:
        type: string
      seven:
        type: string
      eight:
        type: string
      nine:
        type: string
      ten:
        type: string
      eleven:
        type: string
      twelve:
        type: string
      thirteen:
        type: string
      fourteen:
        type: string
      fifteen:
        type: string
      sixteen:
        type: string
      seventeen:
        type: string
      eighteen:
        type: string
      nineteen:
        type: string
      twenty:
        type: string
      twentyone:
        type: string
      twentytwo:
        type: string
      twentythree:
        type: string
  Mamal:
    type: object
    properties:
      birthday: birthday
  Person:
    type: Mamal
    properties:
      hobbies: string[]
      lunchtime: lunchtime
  Adult:
    type: Person
    properties:
      job: string



/books:
  get:
    description: Get all books
    responses:
      200:
        body:
          application/json:
            type: Book[]
  post:
    body:
      application/json:
        type: Book
    responses:
      201:

/books/comicbooks:
  get:
    description: Get all comicbooks
    responses:
      200:
        body:
          application/json:
            type: ComicBook[]
  post:
    body:
      application/json:
        type: ComicBook
    responses:
      201:

/books/comicbooks/scificomicbooks:
  get:
    description: Get all SciFi comicbooks
    responses:
      200:
        body:
          application/json:
            type: SciFiComicBook[]
  post:
    body:
      application/json:
        type: SciFiComicBook
    responses:
      201:

/rest/user:
  !include user.raml

/rest/animals:
  !include animals.raml

/rest/resource/overlap:
  !include overlaps.raml

/rest/emptyobject:
  get:
    responses:
      200:
        body:
          application/json:
            type: empty-object-field
  post:
    body:
      application/json:
        type: empty-object-field
    responses:
      200:
        body:

/cars:
  get:
    responses:
      200:
        body:
          application/json:
            type: car

/simple/string/return:
  get:
    response:
      200:
        body:
          text/html:
            type: string

/rest/zoo:
  get:
    responses:
      200:
        body:
          application/json:
            type: zoo

/rest/twentythreefields:
  post:
    body:
      application/json:
        type: TwentyThreeFields
    responses:
      200:
        body:
          application/json:
            type: TwentyThreeFields

# Todo: fix root path call
#/:
#  get:
#    description: Get the base URL
#    responses:
#      200:
#        body:
#          text/html:
