#%RAML 0.8
---
title: test01
version: 1.0
mediaType: application/json

types:
  link:         !include schemas/link.json
  method:       !include schemas/method.json
  user:         !include schemas/user.json
  animal:       !include schemas/animal.json
  paged-list:   !include schemas/paged-list.json
  tree:         !include schemas/tree.json
  bbox:         !include schemas/geojson/bbox.json
  crs:          !include schemas/geojson/crs.json
  many-fields:  !include schemas/many-fields.json
  geometry:     !include schemas/geojson/geometry.json
  connections:  !include schemas/gurumeditator/connections.json
  messages:     !include schemas/gurumeditator/messages.json
  Book:
    type: object
    properties:
      isbn:
        type: string
        required: true
      title:
        type: string
        required: true
      genre:
        type: string
      author:
        type: Author
        required: true
  Author:
    type: object
    properties:
      firstName:
        type: string
        required: true
      lastName:
        type: string
        required: true
  WithVillain:
    type: object
    properties:
      villain:
        type: string
  ComicBook:
    type: Book
    properties:
      hero:
        type: string
  SciFiComicBook:
    type: ComicBook
    properties:
      era:
        type: string

/books:
  get:
    description: Get all books
    responses:
      200:
        body:
          application/json:
            type: Book[]
  post:
    body:
      application/json:
        type: Book
    responses:
      201:

/books/comicbooks:
  get:
    description: Get all comicbooks
    responses:
      200:
        body:
          application/json:
            type: ComicBook[]
  post:
    body:
      application/json:
        type: ComicBook
    responses:
      201:

/books/comicbooks/scificomicbooks:
  get:
    description: Get all SciFi comicbooks
    responses:
      200:
        body:
          application/json:
            type: SciFiComicBook[]
  post:
    body:
      application/json:
        type: SciFiComicBook
    responses:
      201:

/rest/user:
  !include user.raml

/rest/animals:
  !include animals.raml
